$schema: some-azure-schema-url
type: pipeline
display_name: retail_evaluation_pipeline
description: Evaluation pipeline for UCI Online Retail trained models

# Pipeline settings
settings:
  default_compute: insert_value_here
  default_datastore: insert_value_here
  continue_on_step_failure: false

# Pipeline inputs - by component
### NB: These values are used directly by local_runner.
### The ${{parent.inputs.xxx}} references in the jobs section are Azure ML specific.
inputs:
  # ==========================================
  # EVALUATE MODELS COMPONENT PARAMETERS
  # ==========================================
  evaluate_models__paths_to_models:
    type: string
    default:
      - "models/random_forest_1111.pkl"
      - "models/random_forest_7777_cyclic_day_scaled.pkl"
      - "models/random_forest_7777_cyclic_day_month_scaled.pkl"
  evaluate_models__target_training_data_path:
    type: uri_file
    default: "data/pipeline_runs/train_targets_daily.parquet"
  evaluate_models__target_test_data_path:
    type: uri_file
    default: "data/pipeline_runs/test_targets_daily.parquet"
  evaluate_models__past_covariates_path:
    type: uri_file
    default: "data/pipeline_runs/past_covariates.parquet"
  evaluate_models__future_covariates_path:
    type: uri_file
    default: "data/pipeline_runs/future_covariates.parquet"
  evaluate_models__future_covariates_columns:
    type: string
    default:
      - "is_holiday"
  evaluate_models__past_covariates_columns:
    type: string
    default:
      - "num_transactions"
      - "num_unique_customers"
      - "num_unique_articles"
      - "avg_basket_size"
      - "avg_unit_price"
  evaluate_models__target_column_name:
    type: string
    default: "Quantity"
  evaluate_models__time_column_name:
    type: string
    default: "InvoiceDate"
  evaluate_models__scores_output:
    type: uri_file
    default: "data/pipeline_runs/evaluation_backtest_scores.json"


# Pipeline steps
jobs:
  # Step 1: Evaluate models
  evaluate_models:
    type: command
    component: ../src/components/evaluation/evaluate_models.py
    inputs:
      paths_to_models: ${{parent.inputs.evaluate_models__paths_to_models}}
      target_training_data_path: ${{parent.inputs.evaluate_models__target_training_data_path}}
      target_test_data_path: ${{parent.inputs.evaluate_models__target_test_data_path}}
      past_covariates_path: ${{parent.inputs.evaluate_models__past_covariates_path}}
      future_covariates_path: ${{parent.inputs.evaluate_models__future_covariates_path}}
      future_covariates_columns: ${{parent.inputs.evaluate_models__future_covariates_columns}}
      past_covariates_columns: ${{parent.inputs.evaluate_models__past_covariates_columns}}
      target_column_name: ${{parent.inputs.evaluate_models__target_column_name}}
      time_column_name: ${{parent.inputs.evaluate_models__time_column_name}}
      scores_output: ${{parent.inputs.evaluate_models__scores_output}}
    environment: some-repository:UCI-retail-case@1.2.3
      # Setup versioned image build in CI/CD, and version this yaml file with bumping
      # A single common image for all components to reduce image maintenance.
